#!/bin/sh
# polybar top &
# polybar bottom &
source ~/.config/bspwm/profile
panel &
xsetroot -cursor_name left_ptr
picom &
sxhkd -c ~/.config/bspwm/sxhkdrc &

# Personal
echo 0 >> ~/Documents/Org/Tracking/.concentration
echo bspwm > /tmp/wm
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc rule -a Emacs state=tiled
bspc rule -a firefox:Toolkit state=floating sticky=on
bspc rule -a Zathura state=tiled
#bspc config border_width         2

#bspc config window_gap          -2

bspc config split_ratio          0.50
bspc config borderless_monocle   true
#bspc config single_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true
bspc config pointer_follows_monitor true
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config focused_border_color "#00ff00"
bspc config normal_border_color "#005500"
bspc config border_width 5
sh ~/.config/sxhkd/scripts/session_start.sh
