#!/bin/sh
polybar example &
# polybar bottom &
source ~/.config/bspwm/profile
# panel &
sxhkd -c ~/.config/bspwm/sxhkdrc &
# Keyboard
xcape -e 'Super_L=Escape'
# Personal
echo 0 >> ~/Documents/Org/Tracking/.concentration
echo bspwm > /tmp/wm
bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc config single_monocle true
bspc rule -a Emacs state=tiled
bspc rule -a firefox:Toolkit state=floating sticky=on
bspc rule -a fzf state=fullscreen,floating
bspc rule -a Zathura state=tiled
bspc rule -a Files state=floating
bspc rule -a tabbed state=floating
bspc rule -a Webcam:* state=floating
bspc rule -a Calculator:* state=floating layer=above
#bspc config border_width         2

#bspc config window_gap          -2

bspc config split_ratio          0.50
bspc config borderless_monocle   true
#bspc config single_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true
bspc config pointer_follows_monitor true
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config focused_border_color "#00ff00"
bspc config normal_border_color "#005500"
bspc config border_width 5
#bspc config external_rules_command ~/.config/sxhkd/scripts/rules/masterstack.sh
sh ~/.config/sxhkd/scripts/battery_monitor.sh &
sh ~/.config/sxhkd/scripts/session_start.sh
